In [27]:
import pandas as pd
df = pd.read_csv("hackaton_data_rentals.csv")
df.head()

,rental_id,start_point_lat,start_point_lon,end_point_lat,end_point_lon,started_at,ended_at,user_id,system_name,vehicle_external_id,...,last_checkout_attempt_id,last_checkout_attempt_state,first_odometer_in_meters,first_odometer_recorded_at,last_odometer_in_meters,last_odometer_recorded_at,pause_duration,pause_duration_in_seconds,reservation_at,reservation_point
0,1,41.407661,2.195133,41.427795,2.191177,2016-01-01 00:00:03,2016-01-01 00:13:02,1025384,Barcelona,ES-V-000431,...,2565553.0,succeeded,3745500.0,2016-01-01 00:00:03,3748200.0,2016-01-01 00:13:06,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:54,0101000020E61000005B8EA1AD948F01406B161EEA2DB4...
1,2,40.431644,-3.684857,40.426453,-3.686443,2016-01-01 00:00:18,2016-01-01 01:21:41,1016632,Madrid,ES-MAD-S-000195,...,2566549.0,succeeded,8668800.0,2016-01-01 00:00:18,8681800.0,2016-01-01 01:21:43,0 years 0 mons 0 days 0 hours 19 mins 34.50006...,1174.500065,2015-12-31 23:56:02,0101000020E61000002F1E4001907A0DC0B314B620DE36...
2,3,41.884850,12.490010,41.892765,12.469176,2016-01-01 00:00:21,2016-01-01 00:56:16,1012102,Rome,IT-R-A00292,...,2566203.0,succeeded,494000.0,2016-01-01 00:00:21,502000.0,2016-01-01 00:56:21,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:49:26,0101000020E61000000E38013C58F92840DF72501D06F1...
3,4,41.411480,2.196850,41.411335,2.190067,2016-01-01 00:00:33,2016-01-01 00:05:15,450334,Barcelona,ES-B-A00002,...,2565413.0,succeeded,401000.0,2016-01-01 00:00:33,402000.0,2016-01-01 00:05:18,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:53:01,0101000020E610000041481630819B0140C5ECC094DCB4...
4,5,41.396515,2.151223,41.396538,2.151235,2016-01-01 00:00:34,2016-01-01 00:02:07,1030150,Barcelona,ES-B-A00014,...,2565376.0,succeeded,393000.0,2016-01-01 00:00:34,393000.0,2016-01-01 00:02:12,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:44,0101000020E61000005F39A1E8C2360140DD22319FBEB2...

In [28]:
df = df[df['system_name'] == 'Barcelona']
df.head()

,rental_id,start_point_lat,start_point_lon,end_point_lat,end_point_lon,started_at,ended_at,user_id,system_name,vehicle_external_id,...,last_checkout_attempt_id,last_checkout_attempt_state,first_odometer_in_meters,first_odometer_recorded_at,last_odometer_in_meters,last_odometer_recorded_at,pause_duration,pause_duration_in_seconds,reservation_at,reservation_point
0,1,41.407661,2.195133,41.427795,2.191177,2016-01-01 00:00:03,2016-01-01 00:13:02,1025384,Barcelona,ES-V-000431,...,2565553.0,succeeded,3745500.0,2016-01-01 00:00:03,3748200.0,2016-01-01 00:13:06,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.0,2015-12-31 23:59:54,0101000020E61000005B8EA1AD948F01406B161EEA2DB4...
3,4,41.411480,2.196850,41.411335,2.190067,2016-01-01 00:00:33,2016-01-01 00:05:15,450334,Barcelona,ES-B-A00002,...,2565413.0,succeeded,401000.0,2016-01-01 00:00:33,402000.0,2016-01-01 00:05:18,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.0,2015-12-31 23:53:01,0101000020E610000041481630819B0140C5ECC094DCB4...
4,5,41.396515,2.151223,41.396538,2.151235,2016-01-01 00:00:34,2016-01-01 00:02:07,1030150,Barcelona,ES-B-A00014,...,2565376.0,succeeded,393000.0,2016-01-01 00:00:34,393000.0,2016-01-01 00:02:12,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.0,2015-12-31 23:59:44,0101000020E61000005F39A1E8C2360140DD22319FBEB2...
8,9,41.375774,2.133490,41.375828,2.133465,2016-01-01 00:00:55,2016-01-01 00:02:31,1042724,Barcelona,ES-B-A00036,...,2565379.0,succeeded,303000.0,2016-01-01 00:00:55,303000.0,2016-01-01 00:02:33,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.0,2016-01-01 00:00:37,0101000020E610000055528259FC1101407879DF9D21B0...
9,10,41.396996,2.170572,41.377197,2.158820,2016-01-01 00:01:02,2016-01-01 00:16:55,286426,Barcelona,ES-MAD-S-000615,...,2565575.0,failed,12916000.0,2016-01-01 00:01:02,12919100.0,2016-01-01 00:16:54,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.0,2015-12-31 23:50:02,0101000020E610000033D879C0E15A01407295DD825BB3...

In [35]:
df1000 = df[:60000]
df1000

,rental_id,start_point_lat,start_point_lon,end_point_lat,end_point_lon,started_at,ended_at,user_id,system_name,vehicle_external_id,...,last_checkout_attempt_id,last_checkout_attempt_state,first_odometer_in_meters,first_odometer_recorded_at,last_odometer_in_meters,last_odometer_recorded_at,pause_duration,pause_duration_in_seconds,reservation_at,reservation_point
0,1,41.407661,2.195133,41.427795,2.191177,2016-01-01 00:00:03,2016-01-01 00:13:02,1025384,Barcelona,ES-V-000431,...,2565553.0,succeeded,3745500.0,2016-01-01 00:00:03,3748200.0,2016-01-01 00:13:06,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:54,0101000020E61000005B8EA1AD948F01406B161EEA2DB4...
3,4,41.411480,2.196850,41.411335,2.190067,2016-01-01 00:00:33,2016-01-01 00:05:15,450334,Barcelona,ES-B-A00002,...,2565413.0,succeeded,401000.0,2016-01-01 00:00:33,402000.0,2016-01-01 00:05:18,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:53:01,0101000020E610000041481630819B0140C5ECC094DCB4...
4,5,41.396515,2.151223,41.396538,2.151235,2016-01-01 00:00:34,2016-01-01 00:02:07,1030150,Barcelona,ES-B-A00014,...,2565376.0,succeeded,393000.0,2016-01-01 00:00:34,393000.0,2016-01-01 00:02:12,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:44,0101000020E61000005F39A1E8C2360140DD22319FBEB2...
8,9,41.375774,2.133490,41.375828,2.133465,2016-01-01 00:00:55,2016-01-01 00:02:31,1042724,Barcelona,ES-B-A00036,...,2565379.0,succeeded,303000.0,2016-01-01 00:00:55,303000.0,2016-01-01 00:02:33,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:00:37,0101000020E610000055528259FC1101407879DF9D21B0...
9,10,41.396996,2.170572,41.377197,2.158820,2016-01-01 00:01:02,2016-01-01 00:16:55,286426,Barcelona,ES-MAD-S-000615,...,2565575.0,failed,12916000.0,2016-01-01 00:01:02,12919100.0,2016-01-01 00:16:54,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:50:02,0101000020E610000033D879C0E15A01407295DD825BB3...
10,11,41.362968,2.136852,41.374222,2.126888,2016-01-01 00:01:08,2016-01-01 00:09:55,1011378,Barcelona,ES-MAD-S-000367,...,2565498.0,succeeded,5025600.0,2016-01-01 00:01:08,5027900.0,2016-01-01 00:09:58,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:49:30,0101000020E61000005A7CAFC67E1B0140964EDA0A50AE...
12,13,41.386372,2.150520,41.404823,2.141040,2016-01-01 00:01:12,2016-01-01 00:16:49,902782,Barcelona,ES-MAD-S-000725,...,2565624.0,succeeded,7415400.0,2016-01-01 00:01:12,7419000.0,2016-01-01 00:16:52,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:57:44,0101000020E61000006BE399E150390140CD5DA6817AB1...
13,14,41.386066,2.149840,41.405205,2.139842,2016-01-01 00:01:18,2016-01-01 00:15:21,103144,Barcelona,ES-MAD-S-000469,...,2565592.0,succeeded,5399000.0,2016-01-01 00:01:18,5402600.0,2016-01-01 00:15:23,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:56:49,0101000020E610000047D3C83D193A01407AE4713066B1...
18,19,41.407295,2.162832,41.419193,2.174920,2016-01-01 00:02:23,2016-01-01 00:11:05,677442,Barcelona,ES-MAD-S-000295,...,2565518.0,succeeded,13853400.0,2016-01-01 00:02:23,13855300.0,2016-01-01 00:11:09,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:01:05,0101000020E61000007ECDCD925B4E01408505F7031EB4...
20,21,41.392220,2.197610,41.384655,2.155165,2016-01-01 00:02:33,2016-01-01 00:18:40,965864,Barcelona,ES-V-000289,...,2565649.0,succeeded,11297600.0,2016-01-01 00:02:33,11303100.0,2016-01-01 00:18:43,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:01:45,0101000020E610000002DE5174A394014095482CA435B2...
22,23,41.405739,2.138710,41.405762,2.138778,2016-01-01 00:02:36,2016-01-01 00:03:39,968834,Barcelona,ES-B-A00158,...,2565395.0,succeeded,197000.0,2016-01-01 00:02:36,197000.0,2016-01-01 00:03:44,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:02:26,0101000020E610000034042D52EE1C014004957390F6B3...
23,24,41.385094,2.176700,41.378975,2.187877,2016-01-01 00:02:43,2016-01-01 00:07:49,550456,Barcelona,ES-MAD-S-000699,...,2565466.0,succeeded,8228700.0,2016-01-01 00:02:43,8230200.0,2016-01-01 00:07:53,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:00:27,0101000020E6100000D1114083886601403015FE9D34B1...
26,27,41.389370,2.196398,41.401508,2.200850,2016-01-01 00:02:51,2016-01-01 00:08:20,937588,Barcelona,ES-V-000285,...,2565476.0,succeeded,8476400.0,2016-01-01 00:02:51,8478100.0,2016-01-01 00:08:22,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:56:27,0101000020E6100000084724648690014053144D5CC6B1...
28,29,41.375500,2.157068,41.389008,2.173487,2016-01-01 00:02:59,2016-01-01 00:15:46,1045266,Barcelona,ES-B-A00175,...,2565605.0,succeeded,294000.0,2016-01-01 00:02:59,298000.0,2016-01-01 00:15:49,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:00:39,0101000020E6100000DB05A4FEC3410140BB3F765A12B0...
30,31,41.370968,2.143513,41.379406,2.152328,2016-01-01 00:03:04,2016-01-01 00:09:48,418158,Barcelona,ES-B-A00180,...,2565497.0,succeeded,341000.0,2016-01-01 00:03:04,342000.0,2016-01-01 00:09:52,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:56:21,0101000020E610000020167ED7B809014044DA3DE8FEAE...
31,32,41.396305,2.151528,41.398499,2.142225,2016-01-01 00:03:10,2016-01-01 00:09:36,1018924,Barcelona,ES-B-A00049,...,2565493.0,succeeded,543000.0,2016-01-01 00:03:10,544000.0,2016-01-01 00:09:39,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:02:58,0101000020E61000009AD34D7E7D3601408C223093BBB2...
33,34,41.375141,2.169602,41.369659,2.147403,2016-01-01 00:03:24,2016-01-01 00:25:37,398814,Barcelona,ES-MAD-S-000310,...,2565749.0,succeeded,11719400.0,2016-01-01 00:03:24,11722000.0,2016-01-01 00:25:40,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:09,0101000020E61000000BBEA95A7958014036AAED0DFFAF...
34,35,41.386330,2.159342,41.393753,2.174733,2016-01-01 00:03:27,2016-01-01 00:11:16,508438,Barcelona,ES-B-A00122,...,2565527.0,succeeded,323000.0,2016-01-01 00:03:27,324000.0,2016-01-01 00:11:19,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:51:24,0101000020E6100000FCA81639994201400007289A5DB1...
37,38,41.372040,2.149127,41.371552,2.161047,2016-01-01 00:03:41,2016-01-01 00:11:27,441846,Barcelona,ES-B-A00037,...,2565531.0,succeeded,316000.0,2016-01-01 00:03:41,319000.0,2016-01-01 00:11:31,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:01:54,NaN
38,39,41.374962,2.155848,41.372902,2.173172,2016-01-01 00:03:47,2016-01-01 00:13:33,986614,Barcelona,ES-V-000442,...,2565557.0,succeeded,4698500.0,2016-01-01 00:03:47,4700200.0,2016-01-01 00:13:38,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:53:49,0101000020E6100000A11100F2A43901402D15B25C0EB0...
39,40,41.384144,2.155980,41.404747,2.141422,2016-01-01 00:03:54,2016-01-01 00:20:43,197106,Barcelona,ES-MAD-S-000304,...,2565693.0,succeeded,11788200.0,2016-01-01 00:03:54,11791500.0,2016-01-01 00:20:47,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:01:46,0101000020E61000009677D503E64101406E4A1EF411B1...
40,41,41.408852,2.192307,41.420277,2.204725,2016-01-01 00:04:02,2016-01-01 00:18:19,842878,Barcelona,ES-B-A00111,...,2565645.0,succeeded,342000.0,2016-01-01 00:04:02,345000.0,2016-01-01 00:18:22,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:53,0101000020E6100000F42DD099248A0140FCD24E1957B4...
42,43,41.400116,2.122130,41.409012,2.136378,2016-01-01 00:04:11,2016-01-01 00:09:38,919758,Barcelona,ES-MAD-S-000377,...,2565495.0,succeeded,5275800.0,2016-01-01 00:04:11,5277600.0,2016-01-01 00:09:41,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:59:52,0101000020E61000006B247C6C43F40040305DD7BF43B3...
43,44,41.393848,2.181507,41.383770,2.171050,2016-01-01 00:04:12,2016-01-01 00:16:15,1039762,Barcelona,ES-V-000327,...,2565617.0,succeeded,12792000.0,2016-01-01 00:04:12,12794100.0,2016-01-01 00:16:18,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:00:27,0101000020E6100000DD1100BAB37101403115D67628B2...
44,45,41.411961,2.193630,41.408073,2.160497,2016-01-01 00:04:30,2016-01-01 00:20:46,383802,Barcelona,ES-V-000415,...,2565694.0,succeeded,9544800.0,2016-01-01 00:04:30,9548500.0,2016-01-01 00:20:49,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:56:20,0101000020E6100000402CB8127B8E01409C9DAF0D6CB4...
47,48,41.428566,2.184848,41.380936,2.186513,2016-01-01 00:04:35,2016-01-01 00:30:24,311846,Barcelona,ES-B-A00130,...,2565838.0,succeeded,283000.0,2016-01-01 00:04:35,290000.0,2016-01-01 00:30:27,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:01:58,0101000020E6100000E01140D7F874014036151405DFB6...
49,50,41.402332,2.163765,41.402203,2.163750,2016-01-01 00:04:36,2016-01-01 00:06:15,798038,Barcelona,ES-V-000407,...,2565430.0,succeeded,12801100.0,2016-01-01 00:04:36,12801100.0,2016-01-01 00:06:19,0 years 0 mons 0 days 0 hours 0 mins 38.629187...,38.629187,2016-01-01 00:02:15,0101000020E61000001F5A2BC2E2500140C161B5997AB3...
51,52,41.419521,2.180842,41.408905,2.175697,2016-01-01 00:04:37,2016-01-01 00:11:33,515108,Barcelona,ES-MAD-S-000670,...,2565532.0,succeeded,13433400.0,2016-01-01 00:04:37,13434700.0,2016-01-01 00:11:38,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:00:43,0101000020E610000006003D8848760140FCAFBF92EDB5...
53,54,41.397850,2.147708,41.397850,2.147723,2016-01-01 00:04:56,2016-01-01 00:05:31,181572,Barcelona,ES-MAD-S-000556,...,2565420.0,succeeded,13194000.0,2016-01-01 00:04:56,13194000.0,2016-01-01 00:05:33,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-01 00:04:31,0101000020E6100000BF1EAC74312F0140D3CA6490EAB2...
54,55,41.407490,2.157997,41.405270,2.170720,2016-01-01 00:05:02,2016-01-01 00:15:04,177698,Barcelona,ES-B-A00016,...,2565584.0,succeeded,456000.0,2016-01-01 00:05:02,458000.0,2016-01-01 00:15:08,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2015-12-31 23:53:41,0101000020E61000001FC484871F420140926B54F190B4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121476,121477,41.418079,2.171572,41.407394,2.135957,2016-01-14 07:35:04,2016-01-14 07:53:23,973642,Barcelona,ES-V-000389,...,2740058.0,succeeded,12303500.0,2016-01-14 07:35:04,12307500.0,2016-01-14 07:53:27,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:34:52,0101000020E61000006E3C6893425F01401816C9AD7DB5...
121477,121478,41.380634,2.162985,41.369446,2.187758,2016-01-14 07:35:15,2016-01-14 07:48:25,937308,Barcelona,ES-MAD-S-000381,...,2739971.0,succeeded,5375700.0,2016-01-14 07:35:15,5379700.0,2016-01-14 07:48:28,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:28:25,0101000020E61000001A92D12B2E500140D66147D9BEB0...
121479,121480,41.374168,2.123975,41.392784,2.143438,2016-01-14 07:35:36,2016-01-14 07:50:44,829318,Barcelona,ES-V-000413,...,2740011.0,succeeded,5270400.0,2016-01-14 07:35:36,5273500.0,2016-01-14 07:50:48,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:30:32,0101000020E6100000E988320A38FA00408D953DAEB2AF...
121480,121481,41.396721,2.200163,41.410515,2.214943,2016-01-14 07:35:41,2016-01-14 07:45:16,365948,Barcelona,ES-B-A00249,...,2739938.0,succeeded,35000.0,2016-01-14 07:35:41,37000.0,2016-01-14 07:45:19,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:29:49,0101000020E6100000B38AB8724A9A01401B3CAD27D6B2...
121481,121482,41.411915,2.177805,41.409351,2.190258,2016-01-14 07:35:55,2016-01-14 07:46:15,183784,Barcelona,ES-V-000140,...,2739947.0,succeeded,13442000.0,2016-01-14 07:35:55,13444200.0,2016-01-14 07:46:18,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:32:10,0101000020E6100000D20EC9DAF065014024415D4997B4...
121483,121484,41.388260,2.169923,41.383854,2.140613,2016-01-14 07:36:16,2016-01-14 07:44:58,586636,Barcelona,ES-V-000182,...,2739930.0,succeeded,8681100.0,2016-01-14 07:36:16,8684300.0,2016-01-14 07:45:00,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:30:47,0101000020E6100000CA1180BCCA5F014031153C4BDFB1...
121487,121488,41.372791,2.179557,41.400898,2.197233,2016-01-14 07:36:28,2016-01-14 07:53:34,190346,Barcelona,ES-MAD-S-000437,...,2740060.0,succeeded,4944800.0,2016-01-14 07:36:28,4949100.0,2016-01-14 07:53:37,0 years 0 mons 0 days 0 hours 0 mins 8.927432 ...,8.927432,2016-01-14 07:35:46,0101000020E6100000D7C710F183740140500588F300B0...
121488,121489,41.392395,2.115745,41.395145,2.154552,2016-01-14 07:36:28,2016-01-14 07:47:44,484894,Barcelona,ES-MAD-S-000394,...,2739962.0,succeeded,5167000.0,2016-01-14 07:36:28,5170800.0,2016-01-14 07:47:47,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:34:25,0101000020E61000005BC63AC1D8EC00400000000026B2...
121491,121492,41.378490,2.169912,41.401733,2.191483,2016-01-14 07:36:47,2016-01-14 07:52:39,501040,Barcelona,ES-MAD-S-000337,...,2740049.0,succeeded,8961300.0,2016-01-14 07:36:47,8966100.0,2016-01-14 07:52:44,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:29:31,0101000020E61000003B0EB201005D0140746E5FC7E2B0...
121494,121495,41.397861,2.138000,41.398029,2.180340,2016-01-14 07:37:00,2016-01-14 07:51:47,511518,Barcelona,ES-B-A00159,...,2740039.0,succeeded,335000.0,2016-01-14 07:37:00,339000.0,2016-01-14 07:51:51,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:29:01,0101000020E6100000B86471E6BF18014097080B010CB3...
121495,121496,41.381523,2.181712,41.386597,2.195597,2016-01-14 07:37:06,2016-01-14 07:41:56,830590,Barcelona,ES-MAD-S-000549,...,2739893.0,succeeded,12918400.0,2016-01-14 07:37:06,12919800.0,2016-01-14 07:42:03,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:33:30,0101000020E6100000DAEC7781BC7101405596347EC9B0...
121497,121498,41.399368,2.120045,41.393066,2.141918,2016-01-14 07:37:25,2016-01-14 07:51:34,758280,Barcelona,ES-MAD-S-000558,...,2740035.0,succeeded,12271500.0,2016-01-14 07:37:25,12274700.0,2016-01-14 07:51:38,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:33:13,0101000020E6100000EEFFCB91BEF200409FB2511D48B3...
121498,121499,41.381287,2.162233,41.358692,2.126625,2016-01-14 07:37:34,2016-01-14 07:57:03,673126,Barcelona,ES-MAD-S-000667,...,2740121.0,succeeded,12868100.0,2016-01-14 07:37:34,12872600.0,2016-01-14 07:57:06,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:29:47,0101000020E6100000F98ED08547510140418B5BBBA3B0...
121499,121500,41.412075,2.185668,41.422363,2.187097,2016-01-14 07:37:39,2016-01-14 07:45:29,182302,Barcelona,ES-B-A00326,...,2739942.0,succeeded,17000.0,2016-01-14 07:37:39,19000.0,2016-01-14 07:45:34,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:35:58,0101000020E610000095E93CCF447D01401E4E603AADB4...
121501,121502,41.389568,2.145532,41.382107,2.149745,2016-01-14 07:37:59,2016-01-14 07:44:00,869174,Barcelona,ES-V-000458,...,2739916.0,succeeded,13822400.0,2016-01-14 07:37:59,13824100.0,2016-01-14 07:44:03,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:37:04,0101000020E6100000054C851D6B2B014021393EFFE2B1...
121502,121503,41.399830,2.145102,41.389729,2.165102,2016-01-14 07:38:16,2016-01-14 07:49:00,454506,Barcelona,ES-MAD-S-000639,...,2739981.0,succeeded,8171700.0,2016-01-14 07:38:16,8174100.0,2016-01-14 07:49:05,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:27:35,0101000020E6100000961140DF1A2D01403215D83A34B3...
121506,121507,41.407837,2.150923,41.407207,2.168175,2016-01-14 07:39:05,2016-01-14 07:43:49,275124,Barcelona,ES-MAD-S-000649,...,2739913.0,succeeded,7741100.0,2016-01-14 07:39:05,7742900.0,2016-01-14 07:43:53,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:35:55,0101000020E61000001C1252126D320140263218C858B4...
121509,121510,41.385445,2.147362,41.356014,2.125302,2016-01-14 07:39:07,2016-01-14 08:03:10,851702,Barcelona,ES-MAD-S-000408,...,2740247.0,succeeded,5377700.0,2016-01-14 07:39:07,5382900.0,2016-01-14 08:03:12,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:35:53,0101000020E6100000B644D37E102E014086A0B48185B1...
121511,121512,41.413612,2.197908,41.429932,2.182532,2016-01-14 07:39:13,2016-01-14 07:50:17,130210,Barcelona,ES-MAD-S-000657,...,2739999.0,succeeded,4700300.0,2016-01-14 07:39:13,4702800.0,2016-01-14 07:50:21,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:33:48,0101000020E61000007F2370DA4296014086E28E37F9B4...
121513,121514,41.402805,2.214838,41.394527,2.151567,2016-01-14 07:39:21,2016-01-14 08:08:06,672346,Barcelona,ES-B-A00001,...,2740339.0,succeeded,743000.0,2016-01-14 07:39:21,751000.0,2016-01-14 08:08:10,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:36:22,0101000020E61000008F16A2DD29BC0140083C7C10B8B3...
121516,121517,41.376175,2.131317,41.387295,2.165065,2016-01-14 07:39:23,2016-01-14 07:55:56,182450,Barcelona,ES-MAD-S-000471,...,2740099.0,succeeded,14076000.0,2016-01-14 07:39:23,14080300.0,2016-01-14 07:55:58,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:37:19,0101000020E6100000721180D0760901402F15CC9146B0...
121517,121518,41.386967,2.140788,41.414196,2.177212,2016-01-14 07:39:26,2016-01-14 07:55:27,1015608,Barcelona,ES-MAD-S-000389,...,2740085.0,succeeded,4483700.0,2016-01-14 07:39:26,4489800.0,2016-01-14 07:55:31,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:32:03,0101000020E6100000A479319D8D240140B6FF69BFBCB1...
121518,121519,41.402782,2.149083,41.431847,2.186247,2016-01-14 07:39:30,2016-01-14 07:59:40,312422,Barcelona,ES-MAD-S-000467,...,2740178.0,succeeded,5328100.0,2016-01-14 07:39:30,5334300.0,2016-01-14 07:59:43,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:30:53,0101000020E610000089C82C863B3401400BDB3461A8B3...
121520,121521,41.392807,2.126617,41.392933,2.146522,2016-01-14 07:39:55,2016-01-14 07:49:07,1032110,Barcelona,ES-MAD-S-000379,...,2739984.0,succeeded,5119000.0,2016-01-14 07:39:55,5121100.0,2016-01-14 07:49:12,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:38:20,0101000020E61000007CC4FC188C040140AE855CAA25B2...
121521,121522,41.391624,2.184498,41.401566,2.191377,2016-01-14 07:39:56,2016-01-14 07:50:30,890580,Barcelona,ES-MAD-S-000484,...,2740005.0,succeeded,7459600.0,2016-01-14 07:39:56,7461200.0,2016-01-14 07:50:34,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:31:51,0101000020E61000000E5F7017AB7701401CCEFC6A0EB2...
121522,121523,41.385658,2.185435,41.401413,2.191818,2016-01-14 07:39:58,2016-01-14 07:48:08,868928,Barcelona,ES-MAD-S-000338,...,2739967.0,succeeded,4286300.0,2016-01-14 07:39:58,4288400.0,2016-01-14 07:48:11,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:33:51,0101000020E6100000845E805758760140FF51B91037B1...
121524,121525,41.392159,2.147900,41.382027,2.140602,2016-01-14 07:40:07,2016-01-14 07:48:06,119078,Barcelona,ES-MAD-S-000684,...,2739966.0,succeeded,7605500.0,2016-01-14 07:40:07,7607300.0,2016-01-14 07:48:13,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:37:47,0101000020E6100000C39CA04D0E2F0140BA72AC414EB2...
121526,121527,41.406601,2.152168,41.393875,2.148243,2016-01-14 07:40:16,2016-01-14 07:51:02,411186,Barcelona,ES-MAD-S-000292,...,2740018.0,succeeded,11866300.0,2016-01-14 07:40:16,11868300.0,2016-01-14 07:51:05,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:32:48,0101000020E6100000F6ECCA938A3C014077DD7BF91EB4...
121527,121528,41.397121,2.143875,41.392639,2.161467,2016-01-14 07:40:24,2016-01-14 07:54:49,1029138,Barcelona,ES-V-000460,...,2740071.0,succeeded,13435000.0,2016-01-14 07:40:24,13438500.0,2016-01-14 07:54:54,0 years 0 mons 0 days 0 hours 0 mins 0.00 secs,0.000000,2016-01-14 07:28:47,0101000020E6100000E6D1E8691B2A0140F7B589EEB4B2...

In [36]:
df1000.to_csv(r'2_sem_data_rental.csv')

In [26]:
df1000.to_csv(r'1000_data_rental.csv')